### PR TITLE
Fix searching when there are multiple relations and polymorphism

### PR DESCRIPTION
**Pull request by xprazak2**
If there are multiple relations between classes and some
have polymorphism, we need to make sure that type constraint
is included in query when searching through polymorphic
relations. For the rest, we have to omit the type since
these are 'regular' relations and type column is not present.

My previous fix 80d0a9f3c235d3df49e355bd6750b0728481d8f3
missed this edge case, now I explicitely look for
:polymorphic in options.

### CODE REVIEW

**Comment by ares** [comment]
I tested this in our project for both cases and it fixes the issue that was reintroduced by 4.1.1. Looking at the code, it looks good to me. Adding `condition_many_to_middle` only for relations with polymorphism is the key. Thanks @xprazak2 for thorough tests too.

After this is merged, could we please ask for another release? I know 4.1.1 was released very recently but unfortunately, it fixed one issue while reitroduced second one.

**Comment by wvanbergen** [comment]
👌

**Comment by wvanbergen** [comment]
Thanks for fixing this so quickly and adding tests. I will cut a new release

**Comment by xprazak2** [comment]
Awesome, thanks @wvanbergen!

**Comment by ares** [comment]
@wvanbergen thanks for immediate reaction! @wvanbergen += :1st_place_medal:

**Pull request merged**
