### PR TITLE
Migrate from TravisCI to Github actions

### PR DESCRIPTION
**Pull request by adamruzicka**
Includes:
- https://github.com/wvanbergen/scoped_search/pull/207
- https://github.com/wvanbergen/scoped_search/pull/210

### CODE REVIEW

**Comment by wvanbergen** [comment]
Hello! I am :+1: on moving to GH Actions because Travis appears to be dead. 
I am on a sabbatical though, so if somebody else could make this happen that would be great. :tada: If I need to do anything to get GH actions working, let me know.

As for the test matrix, I'd suggest to stick with the supported Ruby and Rails version.
- For Ruby, only 2.7 and 3.0 are currently supported.
- The oldest Rails version that is still supported is 5.2.
- 
I am OK dropping support for all the older versions of Ruby and Rails.

**Comment by adamruzicka** [comment]
> I am on a sabbatical 

Thank you for chiming in even on your time off, but please don't let us take any more of it away from you :)

> if somebody else could make this happen that would be great.

No worries, leave that to us.

> If I need to do anything to get GH actions working, let me know.

If I recall correctly there's nothing that needs to be done, apart from certain files existing inside the repo. We'll handle this

> As for the test matrix, I'd suggest to stick with the supported Ruby and Rails version.
> I am OK dropping support for all the older versions of Ruby and Rails.

Ack

**Comment by adamruzicka** [comment]
The tests are now green https://github.com/adamruzicka/scoped_search/runs/4105108992

**Review by wvanbergen — APPROVED** [review]

**Review by ares — APPROVED** [review]
Looks good, thanks @adamruzicka and @wvanbergen, merging!

**Pull request merged**
