### PR TITLE
[WIP] configurable date parsing

### PR DESCRIPTION
**Pull request by wvanbergen**
This is a first shot at making date parsing configurable.
- Allow setting a `date_parser` on your definition object. This proc should return a date(time) object, or nil if it cannot be parsed.
- Add a default date parser that simply runs `DateTime.parse`
- `Remove parse_temporal` that uses `eval`.

What do you think of this approach? I'd like to support time spans (e.g. see using `:guess => true` in [Chronic](https://github.com/mojombo/chronic#usage)) so we can get rid of a bunch of logic in `date_test` as well.

@abenari @brocktimus

### CODE REVIEW

**Comment by brocktimus** [comment]
Cursory glance over it, I think we should be passing in "something" which responds to call as opposed to specifically block / lambda / proc syntax. Then you can make any object respond to call and pass it in. For example a method "grabbed" from an object, or a class / object itself with a call method.

Also I prefer passing it as another named argument rather than using a block for aesthetics moreso than any technical reason. Also thought it would be configured in the for each field in the ```scoped_search``` calls, also allows slightly more configurability in that respect.

BTW I think having ```&block``` is redundant unless you're going to do something with it. ```yield if block_given?``` doesn't require the explicit block creation. Only time its needed is if you want to pass the block somewhere or do ```block.call(foo)```.

Bit rambly but I'm just about to go offline, sorry if its a bit rambly. Can flesh out some examples of how I think it'd work from interface here tomorrow if you'd like (and I have time...)?

**Comment by wvanbergen** [comment]
Yeah, any input is welcome! 

I am not in a rush; this PR is just to get the conversation started.

**Comment by wvanbergen** [comment]
So right now, we do accept anything that response to call with one argument: the input value. There's no type checking.

The problem with adding it as an argument (e.g. `scoped_search on: :field, date_parser: proc { ... }`) is that it implies you can set a time parser on a per field basis, which is not the case. We could enable that of course, but IMHO that makes it more complicated and confusing for very little gain: why would you use one date parser on one field and another on a different field.

W.r.t. the block argument: you are completely right, but I always prefer to include it in the method definition for documentation purposes.

**Comment by abenari** [comment]
Looks good to me.
Some commented out tests left in the code.
A sample of usage with Chronics would be helpful.
The auto-completer code suggest some of the removed syntax. see [date_completer](https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/auto_complete_builder.rb#L223)

**Comment by brocktimus** [comment]
So where would the setup go for the date parser if not in ```scoped_search``` call? Probably need to update the README at the same time maybe?

Good point of it isn't a huge gain. Only one I can think of is if you wanted one parser for date fields and another for datetime fields? I can come up with some even more far reaching examples, but thats just me looking for edge cases :-).

**Comment by domcleal** [comment]
> So where would the setup go for the date parser if not in scoped_search call?

Perhaps a Rails initialiser and have a method on ScopedSearch to configure it, e.g. https://github.com/theforeman/foreman/blob/1.8.0/config/initializers/1_fast_gettext.rb#L10

If there's a use for per-field parsers (I can't think of one in our app) then being able to set a default in an initialiser and then on a per-field basis (with a named argument) would perhaps make it both usable and flexible.

You'll need to get the span/min/max dates out of the block rather than just one date in order to replace the code at https://github.com/wvanbergen/scoped_search/blob/v3.2.0/lib/scoped_search/query_builder.rb#L140, plus a completer as @abenari mentioned, perhaps in a separate block?

**Comment by wvanbergen** [comment]
Closing this because the PR is out of date, and I don't have time to revive this in the medium-term future.

**Pull request closed without merging**
