### PR TITLE
Fix query generation when STI is involved

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by wvanbergen** [comment]
I am OK moving to GitHub actions. Looks like this is happening in https://github.com/wvanbergen/scoped_search/pull/212.

**Comment by adamruzicka** [comment]
I don't think the failures on jruby-head are related

**Comment by adamruzicka** [comment]
The same failure happens even without the changes proposed here (see https://github.com/wvanbergen/scoped_search/pull/213)

**Comment by adamruzicka** [comment]
Jruby is borked right now, but apart from it this is green and it has an aproval, merging.

**Pull request merged**
